<?xml version="1.0" encoding="UTF-8"?>

<config>

    <environment>
        <node id="1" master="TRUE">
            <loginInfo ip="10.0.9.54" username="root" password="daemon" port="22" webuser="administrator"
                       webpwd="123456">node25
            </loginInfo>
        </node>
        <node id="2">
            <loginInfo ip="10.0.9.121" username="root" password="daemon" port="22" webuser="administrator"
                       webpwd="123456">node26
            </loginInfo>
        </node>
        <node id="3">
            <loginInfo ip="10.0.9.184" username="root" password="daemon" port="22" webuser="administrator"
                       webpwd="123456">node27
            </loginInfo>
        </node>
    </environment>
    <strategy>
        <log>D:\code\DT\TestCaseLog\</log>
        <order>1</order>
        <paralle>0</paralle>
        <timeout>0</timeout>
        <retype>short</retype>
    <!--paralle 用例运行方式，为0时串行方式，大于0时并行方式，值大小表示并发度大小。取值范围大于等于0的整数。-->
    <!--order 执行顺序，为0时顺序执行，非0时随机执行。取值范围 "0" 和 "1"。-->
    <!--timeout 用例超时时间，单个用例执行最大时间，超时自动停止执行该用例。为 "0" 时表示不设置超时时间。单位为妙。取值范围大于等于0的整数-->
    <!--reptype 用例失败时pytest错误信息详细程度，取值 "auto","long","short","no","line","native"-->
        <!--auto：默认值，如果有多个测试用例失败，仅打印第一个和最后一个用例的回溯信息（格式与long模式一致）-->
        <!--long：最为详尽的回溯信息,包含失败时变量信息-->
        <!--short：仅输出assert的一行以及系统判定内容（不显示上下文）-->
        <!--no：屏蔽全部回溯信息-->r
        <!--line：只使用一行输出显示所有的错误信息-->
        <!--native：只输出Python标准库的回溯信息，不显示额外信息。-->
    </strategy>

    <case>
        <!--<test>C:\Users\Administrator\PycharmProjects\DT\lib\test_001.py</test>-->
        <test>D:\code\DT\TestCase\test_001.py</test>
        <test>D:\code\DT\TestCase\test_002.py</test>
        <!--<test>D:\code\DT\TestCase\test_003.py</test>-->
        <!--<test>D:\code\DT\TestCase\test_setupteardown_example.py</test>-->
    </case>
</config>