{"name": "test_func4", "status": "failed", "statusDetails": {"message": "AssertionError: assert 48 == 5\n +  where 48 = func(47)", "trace": "..\\TestCase\\test_002.py:12: in test_func4\n    assert func(47) == 5\nE   assert 48 == 5\nE    +  where 48 = func(47)"}, "start": 1631957862793, "stop": 1631957862793, "uuid": "66ae6b4e-bfd8-4eb2-aaf3-8a6356d17059", "historyId": "48be1902fc7d35e130116879443c8d1d", "testCaseId": "094ca89a3e041d780214336b27af7d2f", "fullName": "TestCase.test_002#test_func4", "labels": [{"name": "parentSuite", "value": "TestCase"}, {"name": "suite", "value": "test_002"}, {"name": "host", "value": "WIN-28O6201FKQP"}, {"name": "thread", "value": "14176-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCase.test_002"}]}