{"name": "test_3", "status": "failed", "statusDetails": {"message": "AssertionError: assert 48 == 5\n +  where 48 = func(47)", "trace": "..\\TestCase\\test_002.py:16: in test_3\n    assert func(47) == 5\nE   assert 48 == 5\nE    +  where 48 = func(47)"}, "start": 1631957862797, "stop": 1631957862797, "uuid": "d8acb0bb-44e9-4b9c-babc-cee1f0256d71", "historyId": "742c001b6966a7e84de77dea0377c49c", "testCaseId": "8d8a96bb926cf355fe5e7d02f6f00f94", "fullName": "TestCase.test_002#test_3", "labels": [{"name": "parentSuite", "value": "TestCase"}, {"name": "suite", "value": "test_002"}, {"name": "host", "value": "WIN-28O6201FKQP"}, {"name": "thread", "value": "14176-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCase.test_002"}]}