{"name": "test_5", "status": "failed", "statusDetails": {"message": "AssertionError: assert 48 == 5\n +  where 48 = func(47)", "trace": "..\\TestCase\\test_002.py:24: in test_5\n    assert func(47) == 5\nE   assert 48 == 5\nE    +  where 48 = func(47)"}, "start": 1631957862801, "stop": 1631957862802, "uuid": "71044147-f6a6-467b-a78d-5f2d01aa7a7f", "historyId": "87839e30b61b5c25acd966e23f4c1fdd", "testCaseId": "02c1816c4a9ce9718688115439d78fcc", "fullName": "TestCase.test_002#test_5", "labels": [{"name": "parentSuite", "value": "TestCase"}, {"name": "suite", "value": "test_002"}, {"name": "host", "value": "WIN-28O6201FKQP"}, {"name": "thread", "value": "14176-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCase.test_002"}]}