{"name": "test_func2", "status": "failed", "statusDetails": {"message": "AssertionError: assert 4 == 5\n +  where 4 = func(3)", "trace": "..\\TestCase\\test_001.py:19: in test_func2\n    assert func(3) == 5  # 失败示例\nE   assert 4 == 5\nE    +  where 4 = func(3)"}, "start": 1631957862669, "stop": 1631957862670, "uuid": "7c997d4e-0c8e-42f3-83c3-e4c102f721e3", "historyId": "d1f7fdc44fac24f2e1e1180661e86b36", "testCaseId": "c110c5c33c6081c3cf87f10dd4bf4bab", "fullName": "TestCase.test_001#test_func2", "labels": [{"name": "parentSuite", "value": "TestCase"}, {"name": "suite", "value": "test_001"}, {"name": "host", "value": "WIN-28O6201FKQP"}, {"name": "thread", "value": "14176-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCase.test_001"}]}