{"name": "test_4", "status": "failed", "statusDetails": {"message": "AssertionError: assert 48 == 5\n +  where 48 = func(47)", "trace": "..\\TestCase\\test_002.py:20: in test_4\n    assert func(47) == 5\nE   assert 48 == 5\nE    +  where 48 = func(47)"}, "start": 1631957862788, "stop": 1631957862788, "uuid": "cd11a571-e04c-432a-b452-bb7a49231b68", "historyId": "8d4ded987e8614064c10b96c8edbebf6", "testCaseId": "6d684ebb5a8347e85837d91559096a62", "fullName": "TestCase.test_002#test_4", "labels": [{"name": "parentSuite", "value": "TestCase"}, {"name": "suite", "value": "test_002"}, {"name": "host", "value": "WIN-28O6201FKQP"}, {"name": "thread", "value": "14176-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCase.test_002"}]}